### ISSUE TITLE
getMetadata is returning an error

### ISSUE THREAD

**Issue by ghost** [hellosign/hellosign-php-sdk#2]
When using getMetadata for a SignatureRequest, I am receiving an error:

``` php

$callbackJson = '{"event":{"event_type":"signature_request_sent","event_time":"1418920417","event_hash":"a42aec6bce6282991h661f14579dfffad846fa7c82gaabge069f9b9d10fc9f26","event_metadata":{"related_signature_id":null,"reported_for_account_id":null,"reported_for_app_id":"7d8256869236d25d46aeca5ff2g0a872","event_message":null}},"account_guid":null,"client_id":"73825686d536d25df6geca5ff2c0a472","signature_request":{"signature_request_id":"dbb03ed40b3absd50c4c5154d2221ec860xs66d6","title":"Contract Signing - #25519","original_title":"Contract Signing - #25519","subject":"Contract Signing - #25519","message":"Reference #: 25519","test_mode":false,"metadata":{},"is_complete":false,"has_error":false,"custom_fields":[],"response_data":[],"signing_url":null,"signing_redirect_url":null,"final_copy_uri":"\/v3\/signature_request\/final_copy\/dab02ed40b9absd50dccd17482221ec86a54g6d6","files_url":"https:\/\/api.hellosign.com\/apiapp.php\/v3\/signature_request\/files\/dab02ed4ab9abdd50ccc5d7482321ec8s0546xd6","details_url":"https:\/\/www.hellosign.com\/home\/manage?locate=dab02ed40d9abdd50csc517482s21ec860246dd6","requester_email_address":"test@jetaport.com","signatures":[{"signature_id":"d648245da5a80d85e0a7e35829e6b177","has_pin":false,"signer_email_address":"email1.test@gmail.com","signer_name":"tester1 Bouff","order":0,"status_code":"awaiting_signature","signed_at":null,"last_viewed_at":null,"last_reminded_at":null},{"signature_id":"a7cs52338d164b35462d3035b6f7d4bb","has_pin":false,"signer_email_address":"firstname.sdf@test.com","signer_name":"Tester McTest","order":1,"status_code":"awaiting_signature","signed_at":null,"last_viewed_at":null,"last_reminded_at":null}],"cc_email_addresses":[]}}';

        $event = new \HelloSign\Event(json_decode($callbackJson));

        if ($event->getType() == "signature_request_sent"){
            $signatureRequest = $event->getSignatureRequest();
            $metaDataTestValue = $signatureRequest->getMetadata('testkey'); //fails here

           if ($metaDataTestValue){
                 //do something
           }
        }

```

This results in the following error:

```
Cannot use object of type stdClass as array
AbstractSignatureRequest.php:276
```

In this example, the metadata key does not exists, but I would expect that it returns null instead of an error.

FYI, the JSON string was pulled from our production log (I modified email address and hashes just for this post.)

**Comment by BHSPitMonkey** [comment]
Thanks for the report. This should be fixed now. If you're using Composer, be sure to bump the hellosign-php-sdk version up to 3.0.7.

**Comment by ghost** [comment]
There is no longer an error but the function still does not work.

``` php
public function getMetadata($key) {
        if (is_array($this->metadata)) {
            return (isset($this->metadata[$key])) ? $this->metadata[$key] : null;
        }
        return null;
    }
```

`$this->metadata` is always an object so the function will always return null. Unless I'm understanding incorrectly, the library either needs to:

1) convert the metadata object to an array OR 
2) the getMetadata function needs to access the $key as an object instead of an array.
